# Generated by Django 3.2.11 on 2022-04-01 13:14

import He_Loveapp.models
import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(default='Hello !', max_length=300)),
                ('rank', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(default='userimages/defaultUserPP.png', upload_to=He_Loveapp.models.user_Image_Files_directory_path)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_interest_interest', to='He_Loveapp.interest')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_interest_user', to='He_Loveapp.appuser')),
            ],
            options={
                'verbose_name_plural': 'User_interests',
            },
        ),
        migrations.CreateModel(
            name='User_gender_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_gender_interest_gender', to='He_Loveapp.gender')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_gender_interest_user', to='He_Loveapp.appuser')),
            ],
            options={
                'verbose_name_plural': 'User_gender_interests',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=He_Loveapp.models.user_Image_Files_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_user_1', models.BooleanField(null=True)),
                ('vote_user_2', models.BooleanField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_message_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user_1', to='He_Loveapp.appuser')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user_2', to='He_Loveapp.appuser')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='eventimages/default-Event.png', upload_to=He_Loveapp.models.event_upload)),
                ('participants', models.ManyToManyField(to='He_Loveapp.AppUser')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_user', to='He_Loveapp.appuser')),
                ('user_disliked', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_user_disliked', to='He_Loveapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_match', to='He_Loveapp.match')),
                ('user_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user_receiver', to='He_Loveapp.appuser')),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user_sender', to='He_Loveapp.appuser')),
            ],
            options={
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='user_gender', to='He_Loveapp.gender'),
        ),
    ]
