# Generated by Django 3.2.11 on 2022-02-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gender', to='He_Loveapp.gender'),
        ),
        migrations.CreateModel(
            name='User_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interest_interest_id', to='He_Loveapp.interest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interest_user_id', to='He_Loveapp.user')),
            ],
            options={
                'verbose_name_plural': 'User_interests',
            },
        ),
        migrations.CreateModel(
            name='User_gender_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gender_interest_gender_id', to='He_Loveapp.gender')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gender_interest_user_id', to='He_Loveapp.user')),
            ],
            options={
                'verbose_name_plural': 'User_interests',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.TextField(blank=True, db_column='file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_user', to='He_Loveapp.user')),
            ],
            options={
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_message_date', models.DateField()),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user_1', to='He_Loveapp.user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user_2', to='He_Loveapp.user')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('user_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user_receiver', to='He_Loveapp.user')),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user_sender', to='He_Loveapp.user')),
            ],
            options={
                'verbose_name_plural': 'Chats',
            },
        ),
    ]
