# Generated by Django 3.2.11 on 2022-03-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0002_auto_20220224_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='vote_user_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='vote_user_2',
            field=models.BooleanField(null=True),
        ),
    ]
