# Generated by Django 3.2.11 on 2022-03-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0003_auto_20220303_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_gender_interest',
            options={'verbose_name_plural': 'User_gender_interests'},
        ),
    ]
