# Generated by Django 3.2.11 on 2022-03-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0003_auto_20220310_1324'),
        ('He_Loveapp', '0004_alter_user_gender_interest_options'),
    ]

    operations = [
    ]
