# Generated by Django 3.2.11 on 2022-03-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0005_merge_20220310_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='_file',
        ),
        migrations.AddField(
            model_name='picture',
            name='path',
            field=models.ImageField(default='defaultUserImage.png', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
