# Generated by Django 3.2.11 on 2022-03-10 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0005_merge_20220310_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='gender_interest',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='user_gender_interest', to='He_Loveapp.gender'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='description',
            field=models.TextField(default='Hello !'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='user_gender', to='He_Loveapp.gender'),
        ),
    ]
