# Generated by Django 3.2.11 on 2022-03-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0007_remove_appuser_gender_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user_receiver', to='He_Loveapp.appuser'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user_sender', to='He_Loveapp.appuser'),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user_1', to='He_Loveapp.appuser'),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user_2', to='He_Loveapp.appuser'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_user', to='He_Loveapp.appuser'),
        ),
        migrations.AlterField(
            model_name='user_gender_interest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gender_interest_user_id', to='He_Loveapp.appuser'),
        ),
        migrations.AlterField(
            model_name='user_interest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interest_user_id', to='He_Loveapp.appuser'),
        ),
    ]
