# Generated by Django 3.2.11 on 2022-03-24 13:34

import He_Loveapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0007_alter_picture_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profilePicture',
            field=models.ImageField(default='temp', upload_to='TODO_CHANGE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.ImageField(upload_to=He_Loveapp.models.user_Image_Files_directory_path),
        ),
    ]
