# Generated by Django 3.2.11 on 2022-03-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0010_auto_20220316_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
