# Generated by Django 3.2.11 on 2022-03-16 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0011_appuser_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
