# Generated by Django 3.2.11 on 2022-03-23 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0012_auto_20220316_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_user', to='He_Loveapp.appuser')),
                ('user_disliked', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_user_disliked', to='He_Loveapp.appuser')),
            ],
        ),
    ]
