# Generated by Django 3.2.11 on 2022-03-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0012_auto_20220316_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='match',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_match', to='He_Loveapp.match'),
        ),
    ]
