# Generated by Django 3.2.11 on 2022-03-24 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0013_chat_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
