# Generated by Django 3.2.11 on 2022-03-23 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0013_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
