# Generated by Django 3.2.11 on 2022-03-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0008_auto_20220324_1434'),
        ('He_Loveapp', '0014_alter_dislike_date'),
    ]

    operations = [
    ]
