# Generated by Django 3.2.11 on 2022-03-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0014_alter_chat_date'),
        ('He_Loveapp', '0015_merge_0008_auto_20220324_1434_0014_alter_dislike_date'),
    ]

    operations = [
    ]
