# Generated by Django 3.2.11 on 2022-03-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0015_alter_appuser_description'),
        ('He_Loveapp', '0016_merge_20220328_1639'),
    ]

    operations = [
    ]
