# Generated by Django 3.2.11 on 2022-03-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0018_auto_20220330_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_match', to='He_Loveapp.match'),
        ),
    ]
