# Generated by Django 3.2.11 on 2022-03-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0018_auto_20220331_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='src/vue/files/img/default-Event.png'),
        ),
    ]
