# Generated by Django 3.2.11 on 2022-03-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0019_alter_chat_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_match', to='He_Loveapp.match'),
        ),
    ]
