# Generated by Django 3.2.11 on 2022-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0019_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='eventimages/default-Event.png'),
        ),
    ]
