# Generated by Django 3.2.11 on 2022-03-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0017_merge_20220329_1942'),
        ('He_Loveapp', '0019_alter_chat_match'),
    ]

    operations = [
    ]
