# Generated by Django 3.2.11 on 2022-03-31 12:33

import He_Loveapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0020_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendieces',
            field=models.ManyToManyField(to='He_Loveapp.AppUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='eventimages/default-Event.png', upload_to=He_Loveapp.models.event_upload),
        ),
    ]
