# Generated by Django 3.2.11 on 2022-04-02 14:04

import He_Loveapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0021_rename_profilepicture_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=He_Loveapp.models.user_Image_Files_directory_path),
        ),
    ]
