# Generated by Django 3.2.11 on 2022-03-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0021_auto_20220331_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendieces',
            new_name='participants',
        ),
    ]
