# Generated by Django 3.2.11 on 2022-03-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0021_rename_profilepicture_appuser_profile_picture'),
        ('He_Loveapp', '0022_rename_attendieces_event_participants'),
    ]

    operations = [
    ]
