# Generated by Django 3.2.11 on 2022-03-31 13:43

import He_Loveapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0023_merge_20220331_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(default='userimages/default.png', upload_to=He_Loveapp.models.user_Image_Files_directory_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='eventimages/default-Event.png', upload_to=He_Loveapp.models.event_upload),
        ),
    ]
