# Generated by Django 3.2.11 on 2022-03-31 13:46

import He_Loveapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('He_Loveapp', '0024_auto_20220331_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(default='userimages/defaultUserPP.png', upload_to=He_Loveapp.models.user_Image_Files_directory_path),
        ),
    ]
